package immutableClass;

public class Main {

	public static void main(String[] args) {
		System.out.println("----------------------Vector------------------------");
		double[] a = { 1, 2, 3, 4, 5 };
		double[] b = { 1, 1, 1, 1, 1 };
		double c = 0;
		Vector aVector = new Vector(a);
		Vector bVector = new Vector(b);
		Vector cVector = Vector.Plus(aVector, bVector);
		System.out.println();
		System.out.println("Plus: " + cVector.toString());
		System.out.println("aVector: " + aVector.toString());
		System.out.println("bVector: " + bVector.toString());
		cVector = Vector.Minus(aVector, bVector);
		System.out.println();
		System.out.println("Minus: " + cVector.toString());
		System.out.println("aVector: " + aVector.toString());
		System.out.println("bVector: " + bVector.toString());
		c = Vector.Dot(aVector, bVector);
		System.out.println();
		System.out.println("Dot Product: " + c);
		System.out.println("aVector: " + aVector.toString());
		System.out.println("bVector: " + bVector.toString());
		cVector.set(0, 100);
		System.out.println();
		System.out.println("Set cVector: " + cVector.toString());
		System.out.println("changeTo: " + cVector.get(0));

		System.out.println();
		System.out.println("----------------UnmodifiableVector---------------------");
		UnmodifiableVector aUnmodifiableVector = new UnmodifiableVector(a);
		UnmodifiableVector bUnmodifiableVector = new UnmodifiableVector(b);
		UnmodifiableVector cUnmodifiableVector = UnmodifiableVector.Plus(aUnmodifiableVector, bUnmodifiableVector);
		System.out.println();
		System.out.println("Plus: " + cUnmodifiableVector.toString());
		System.out.println("aUnmodifiableVector: " + aUnmodifiableVector.toString());
		System.out.println("bUnmodifiableVector: " + bUnmodifiableVector.toString());
		cUnmodifiableVector = UnmodifiableVector.Minus(aUnmodifiableVector, bUnmodifiableVector);
		System.out.println();
		System.out.println("Minus: " + cUnmodifiableVector.toString());
		System.out.println("aUnmodifiableVector: " + aUnmodifiableVector.toString());
		System.out.println("bUnmodifiableVector: " + bUnmodifiableVector.toString());
		c = UnmodifiableVector.Dot(aUnmodifiableVector, bUnmodifiableVector);
		System.out.println();
		System.out.println("Dot Product: " + c);
		System.out.println("aUnmodifiableVector: " + aUnmodifiableVector.toString());
		System.out.println("bunmodifiableVector: " + bUnmodifiableVector.toString());
		cUnmodifiableVector.set(0, 100);
		System.out.println();
		System.out.println("Set cUnmodifiableVector: " + cUnmodifiableVector.toString());
		System.out.println("changeTo: " + cUnmodifiableVector.get(0));
		UnmodifiableVector dUnmodifiableVector = cUnmodifiableVector.set(0, 100);
		System.out.println("Set cUnmodifiableVector to dUnmodifiableVector: " + dUnmodifiableVector.toString());

		System.out.println();
		System.out.println("--------------------Matrix--------------------------");
		double[][] aa = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } };
		double[][] bb = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } };
		Matrix aMatrix = new Matrix(aa);
		Matrix bMatrix = new Matrix(bb);
		Matrix cMatrix = Matrix.Plus(aMatrix, bMatrix);
		System.out.println();
		System.out.println("Plus:\n" + cMatrix.toString());
		System.out.println("aMatrix:\n" + aMatrix.toString());
		System.out.println("bMatrix:\n" + bMatrix.toString());
		System.out.println();
		cMatrix = Matrix.Minus(aMatrix, bMatrix);
		System.out.println("Minus:\n" + cMatrix.toString());
		System.out.println("aMatrix:\n" + aMatrix.toString());
		System.out.println("bMatrix:\n" + bMatrix.toString());
		System.out.println();
		cMatrix = Matrix.Dot(aMatrix, bMatrix);
		System.out.println("Dot Product:\n" + cMatrix);
		System.out.println("aMatrix:\n" + aMatrix.toString());
		System.out.println("bMatrix:\n" + bMatrix.toString());
		System.out.println();
		cMatrix.set(0, 0, 100);
		System.out.println("Set cMatrix:\n" + cMatrix.toString());
		System.out.println("changeTo:\n" + cMatrix.get(0, 0));

		System.out.println();
		System.out.println("-------------------UnmodifiableMatrix------------------------");
		UnmodifiableMatrix aUnmodifiableMatrix = new UnmodifiableMatrix(aa);
		UnmodifiableMatrix bUnmodifiableMatrix = new UnmodifiableMatrix(bb);
		UnmodifiableMatrix cUnmodifiableMatrix = UnmodifiableMatrix.Plus(aUnmodifiableMatrix, bUnmodifiableMatrix);
		System.out.println();
		System.out.println("Plus:\n" + cUnmodifiableMatrix.toString());
		System.out.println("aUnmodifiableMatrix:\n" + aUnmodifiableMatrix.toString());
		System.out.println("bUnmodifiableMatrix:\n" + bUnmodifiableMatrix.toString());
		System.out.println();
		cUnmodifiableMatrix = UnmodifiableMatrix.Minus(aUnmodifiableMatrix, bUnmodifiableMatrix);
		System.out.println("Minus:\n" + cUnmodifiableMatrix.toString());
		System.out.println("aUnmodifiableMatrix:\n" + aUnmodifiableMatrix.toString());
		System.out.println("bUnmodifiableMatrix:\n" + bUnmodifiableMatrix.toString());
		System.out.println();
		cUnmodifiableMatrix = UnmodifiableMatrix.Dot(aUnmodifiableMatrix, bUnmodifiableMatrix);
		System.out.println("Dot Product:\n" + cUnmodifiableMatrix);
		System.out.println("aUnmodifiableMatrix:\n" + aUnmodifiableMatrix.toString());
		System.out.println("bUnmodifiable  Matrix:\n" + bUnmodifiableMatrix.toString());
		System.out.println();
		cMatrix.set(0, 0, 100);
		System.out.println("Set cMatrix:\n" + cUnmodifiableMatrix.toString());
		System.out.println("changeTo:\n" + cUnmodifiableMatrix.get(0, 0));
		UnmodifiableMatrix dUnmodifiableMatrix = cUnmodifiableMatrix.set(0, 0, 100);
		System.out.println("Set cUnmodifiableMatrix to dUnmodifiableMatrix:\n" + dUnmodifiableMatrix.toString());

		System.out.println();
		System.out.println("-------------------MathUtils------------------------");
		System.out.println();
		System.out.println("***********Vector************");
		Vector vector1 = new Vector(a);
		Vector vector2 = new Vector(b);
		System.out.println("vector1: " + vector1.toString());
		System.out.println("vector2: " + vector2.toString());
		System.out.println("change:");
		vector1 = vector2;
		vector2.set(2, 40);
		System.out.println("vector1: " + vector1.toString());
		System.out.println("vector2: " + vector2.toString());
		System.out.println();
		System.out.println("***********UnmodifiableVector************");
		UnmodifiableVector vector3 = MathUtils.getUnmodifiableVector(vector1);
		System.out.println("vector3: " + vector3.toString());
		System.out.println("change:");
		UnmodifiableVector vector4 = vector3.set(4, 80);
		vector3 = vector3.set(1, 1000);
		System.out.println("vector3: " + vector3.toString());
		System.out.println("vector4: " + vector4.toString());

		System.out.println();
		System.out.println("***********Matrix************");
		Matrix matrix1 = new Matrix(aa);
		Matrix matrix2 = new Matrix(bb);
		System.out.println("matrix1:\n" + matrix1.toString());
		System.out.println("matrix2:\n" + matrix2.toString());
		System.out.println("change:");
		matrix1 = matrix2;
		matrix2.set(1, 1, 40);
		System.out.println("matrix1:\n" + matrix1.toString());
		System.out.println("matrix2:\n" + matrix2.toString());
		System.out.println();
		System.out.println("***********UnmodifiableMatrix************");
		UnmodifiableMatrix matrix3 = MathUtils.getUnmodifiableMatrix(matrix1);
		System.out.println("matrix3:\n" + matrix3.toString());
		System.out.println("change:");
		UnmodifiableMatrix matrix4 = matrix3.set(2, 2, 80);
		matrix3 = matrix3.set(1,2, 1000);
		System.out.println("matrix3:\n" + matrix3.toString());
		System.out.println("matrix4:\n" + matrix4.toString());
	}
}
